# SPDX-FileCopyrightText: Copyright (c) 2021-2025, NVIDIA CORPORATION.
# SPDX-License-Identifier: Apache-2.0

{% set version = environ['RAPIDS_PACKAGE_VERSION'].lstrip('v') %}
{% set cuda_version = '.'.join(environ['RAPIDS_CUDA_VERSION'].split('.')[:2]) %}
{% set cuda_major = cuda_version.split('.')[0] %}
{% set date_string = environ['RAPIDS_DATE_STRING'] %}


package:
  name: libcucim
  version: {{ version }}

source:
  path: ../../..

build:
  number: {{ GIT_DESCRIBE_NUMBER }}
  string: cuda{{ cuda_major }}_{{ date_string }}_gh{{ GIT_DESCRIBE_HASH }}_gn{{ GIT_DESCRIBE_NUMBER }}_ph{{ PKG_HASH }}
  ignore_run_exports:
    - openslide
  ignore_run_exports_from:
    - {{ compiler('cuda') }}
    - cuda-cudart-dev
    - libcufile-dev
    - libnvjpeg-dev
  script_env:
    - AWS_ACCESS_KEY_ID
    - AWS_SECRET_ACCESS_KEY
    - AWS_SESSION_TOKEN
    - CMAKE_C_COMPILER_LAUNCHER
    - CMAKE_CUDA_COMPILER_LAUNCHER
    - CMAKE_CXX_COMPILER_LAUNCHER
    - CMAKE_GENERATOR
    - PARALLEL_LEVEL
    - SCCACHE_BUCKET
    - SCCACHE_IDLE_TIMEOUT
    - SCCACHE_REGION
    - SCCACHE_S3_KEY_PREFIX=libcucim-aarch64 # [aarch64]
    - SCCACHE_S3_KEY_PREFIX=libcucim-linux64 # [linux64]
    - SCCACHE_S3_USE_SSL
    - SCCACHE_S3_NO_CREDENTIALS

requirements:
  build:
    - {{ compiler("c") }}
    - {{ compiler("cxx") }}
    - {{ compiler('cuda') }}
    - cuda-version ={{ cuda_version }}
    - binutils
    - cmake {{ cmake_version }}
    - make
    - ninja
    - {{ stdlib("c") }}
    - yasm # [x86_64]
  host:
    - cuda-version ={{ cuda_version }}
    - cuda-cudart-dev
    - libcufile-dev
    - libnvjpeg-dev
    - libnvimgcodec-dev {{ nvimgcodec_version }}  # nvImageCodec development headers and libraries
    - nvtx-c >=3.1.0
    - openslide
  run:
    {% if cuda_major == "12" %}
    - {{ pin_compatible('cuda-version', lower_bound='12.2', upper_bound='13.0a0') }}
    {% else %}
    - {{ pin_compatible('cuda-version', max_pin='x', min_pin='x') }}
    {% endif %}
    - libcufile
    - cuda-cudart
    - libnvjpeg
    - libnvimgcodec0 {{ nvimgcodec_version }}  # nvImageCodec runtime library
  run_constrained:
    - {{ pin_compatible('openslide') }}
    - libnvimgcodec-dev {{ nvimgcodec_version }}  # Optional: for development/debugging

about:
  home: https://developer.nvidia.com/multidimensional-image-processing
  summary: libcucim C++ library
  license: Apache-2.0
  license_family: Apache
  license_file:
    - LICENSE
    - LICENSE-3rdparty.md
  doc_url: https://docs.rapids.ai/api/cucim/stable/
  dev_url: https://github.com/rapidsai/cucim
