#
# Copyright (c) 2020, NVIDIA CORPORATION.
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
FROM nvcr.io/nvidian/dlmed/clara-train-sdk:v3.1-ga-qa-5

RUN apt-get update \
    && apt-get install --yes --fix-missing --no-install-recommends \
        libopenslide0 \
    && rm -rf /var/lib/apt/lists/*

COPY ./docker/requirements-claratrain.txt ./
COPY ./*.whl ./

# Use `python -m pip` to avoid using an old script wrapper.
RUN python -m pip install --no-cache-dir --upgrade pip setuptools wheel \
    && python -m pip install --no-cache-dir -r requirements-claratrain.txt \
    && python -m pip install cu*.whl
