#!/bin/bash
#
# Copyright (c) 2021, NVIDIA CORPORATION.
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

SCRIPT_DIR=$(dirname "$(readlink -f "$0")")

if [ -e ${SCRIPT_DIR}/debug_env.sh ]; then
    # User can place debug_env.sh in the same directory as this script (scripts/debug_env.sh would be ignored in git repo)
    . ${SCRIPT_DIR}/debug_env.sh
elif [ -e ${SCRIPT_DIR}/../.python-version ]; then
    # Need to init in script: https://github.com/pyenv/pyenv-virtualenv/issues/204
    eval "$(pyenv init -)"
    eval "$(pyenv virtualenv-init -)"
    # Above will do `pyenv activate $(cat ${SCRIPT_DIR}/../.python-version)`.
else
    echo "Environment file not found. Exiting."
    exit 1
fi
echo "Python: $(python3 -c "import sys;print(sys.executable)")"
exec env python3 "$@"
